[context."production".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://sv-mini-atlas-pr-36.herokuapp.com/graphql/"
[context."27-multi-folio".environment]
  VUE_APP_ATLAS_GRAPHQL_ENDPOINT = "https://sv-mini-atlas-pr-36.herokuapp.com/graphql/"
