name: Build Vue 3 + Pinia + Vite
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'glengemann'
          reponame: 'frontend'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          useyarn: true
