name: CI

on:
  push:
    branches:
      - "**"
    paths:
      - 'packages/**'
      - 'src/**'
      - .github/workflows/ci.yml

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Run linting checks
        run: yarn run lint
