name: CI

on:
  push:
    branches:
      - "**"
    paths:
      - 'packages/**'
      - 'src/**'
      - .github/workflows/ci.yml

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install deps using Yarn from Cache
        uses: bahmutov/npm-install@v1.4.3
      - name: Run linting checks
        run: yarn run lint
